### ISSUE TITLE
I cant add a PI to a existing ART

### ISSUE THREAD

**Issue by MichaelHem** [solidify/scale#27] opened 2023-11-08 14:35 UTC
**Describe the bug**
I am not able to add a PI to an existing ART is does not work with an exiating PI to add the Itertions, and it does not work to add a New PI it never appears in teh @Scale Addon ion DevOps 
**To Reproduce**
1. Go to @scale addon in DEVOps
2. Click on Add a existing PI to the ART
3. Scroll down to select Iteration Path in upcoming Window
4. toggle add Iterations to team Sprints
5. Click Create

**Expected behavior**
I will see in teh @scale Addon a New PI with all define Iterations, also all Itrérations are added to all Team Sprints

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - BrowserChrome, or edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MOlausson** [comment] 2023-11-08 15:39
@MichaelHem can you send an email to support.scale@solidify.dev? If you can share information about your Azure DevOps environment we can take it from there.

**Comment by JimmyKB** [comment] 2023-11-20 11:49
Me & @MichaelHem had a meeting and the reason why it didn't work is because they had disabled the PI-work item type.
Now it works as intended. Closing this ticket now 👍

**Closed by JimmyKB** 2023-11-20 11:49 UTC
